spring.config.activate.on-profile=mysql

spring.datasource.url=jdbc:mysql://127.0.0.1/crud_angular?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



