spring.application.name=springbootsaasapi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.profiles.active=postgres

jwt.secret=8M7gVa1zH/4N9eY0pC6K3aZhv1Xkuz0BHiM5F4e2xs8=
jwt.expiration=86400000

spring.data.redis.url=redis://localhost:6379



